### ISSUE TITLE
Question - Susy templates

### ISSUE THREAD

**Issue by MortalCatalyst** [pzi/middleman-basis#5]
Hi

Is it hard to fork or just add susy as a dependancy so I can use their grids?

**Comment by pzi** [comment]
Hi Sayth,

Although I haven't used Susy myself yet, it should be straight forward really:

In your Gemfile, at the bottom, add

``` ruby
gem 'susy'
```

and in the main Sass file, add

``` sass
@import "susy"
```

Let me know how you go :)

Cheers

Patrik
